language: objective-c
osx_image: xcode9

before_install:
  - env
  - locale
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

script: ci/buildViaTravis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    secure: lLdhsSPyAPxGMkPA/9ZIFwKIgIhQuHuHPxsXZkfG3cRj3SbESIHQXzEAzWGIB/wH3SIjCJjAlHBVxyrvPhNHOHPj9bPNpvJzcHs1Zhh7L5ooRRI8aQikVpiziONXgrimzE99Pu88s+jk7V+dp08I8H8xzsHclZrlOkCUq+IatEMsyBm+bgBJKxYe8FBd7Acr2AHIdPc88NboLIRbz0NPf/wCpL8HVt1l1DYXL1aAEqmAxbHZyyEA0AYQG/VVMT/CPkZHNy+igeLYyHswRizT0OII747HKEhRdLTGgNviKbbQPRclhvUD0Jxr6RFk2R/Y1Fhz25/N9dl1UirSHmRbTGESTjQIvKxdqIm+1JpckwglSpWYBFI3/hI4+i3tnugWoy9U54cM9QrdYlwfwM8gc3/KXkSh8b2kS+QKfKo55WFGxrQmn/foM0qv3g/IsJnJX3xoumwmz3wD8QcCgm1TvU1VcMWKsMLBn0OAasVEBZ+8PsWyRZHViewqKuxsEzhjqsdYNe41Z8VQfKpm4Nk4TrDr/OnWQv8+v93qI0pqs0JzBcgzKTvNHIv5WSXfAt2gkIXlkndXOqOlAH4aP470V4g1ail0bmulxCwd84VfbfJuKC35dWTRnPWpno7Y+gFHCX9GGoQnzuj6UbEvjDnQ8XyGw0gyGTR0qVzuoi9ifQw=
